services:
  remix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 5173:5173
    command: sh -c "bun i && bun run dev"
